import type { MusicStyleId } from '../musicStyles.ts'
import { getMusicProviderLabel, type MusicTrackDescriptor } from './types.ts'

interface LocalFallbackTrackDefinition extends MusicTrackDescriptor {
  styleId: MusicStyleId
}

const PROVIDER_LABEL = getMusicProviderLabel('local-fallback')

const LOCAL_FALLBACK_TRACK_DEFINITIONS: LocalFallbackTrackDefinition[] = [
  {
    id: 'local-fallback:acoustic-pop-breeze-01',
    styleId: 'acoustic-pop-breeze',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Open Road Acoustic',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/acoustic-pop-breeze.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:piano-focus-01',
    styleId: 'piano-focus',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Ivory Focus',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/piano-focus.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:blues-lane-01',
    styleId: 'blues-lane',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Blue Lane Shuffle',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/blues-lane.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:folk-pop-trail-01',
    styleId: 'folk-pop-trail',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Campfire Carousel',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/folk-pop-trail.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:reggae-sun-01',
    styleId: 'reggae-sun',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Island Skank',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/reggae-sun.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:ska-skank-01',
    styleId: 'ska-skank',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'City Ska Sprint',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/ska-skank.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:brit-pop-bounce-01',
    styleId: 'brit-pop-bounce',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Anthem On The Roof',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/brit-pop-bounce.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:funk-rock-jam-01',
    styleId: 'funk-rock-jam',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Bassline Ignition',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/funk-rock-jam.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:pop-rock-drive-01',
    styleId: 'pop-rock-drive',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Radio Drive',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/pop-rock-drive.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:surf-rock-roll-01',
    styleId: 'surf-rock-roll',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Saltwater Twang',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/surf-rock-roll.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:alternative-rock-pulse-01',
    styleId: 'alternative-rock-pulse',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Neon Alt Pulse',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/alternative-rock-pulse.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:garage-rock-01',
    styleId: 'garage-rock',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Basement Static',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/garage-rock.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:punk-rock-spark-01',
    styleId: 'punk-rock-spark',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Fast Lane Riot',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/punk-rock-spark.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:hard-rock-charge-01',
    styleId: 'hard-rock-charge',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Chrome Riff Charge',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/hard-rock-charge.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
  {
    id: 'local-fallback:heavy-metal-storm-01',
    styleId: 'heavy-metal-storm',
    provider: 'local-fallback',
    providerLabel: PROVIDER_LABEL,
    title: 'Steel Storm Run',
    artist: 'Schiebepuzzle',
    audioUrl: '/audio/music/heavy-metal-storm.wav',
    trackUrl: null,
    providerUrl: null,
    licenseLabel: 'Lokale App-Datei',
    isFallback: true,
  },
]

const LOCAL_FALLBACK_TRACKS_BY_STYLE = LOCAL_FALLBACK_TRACK_DEFINITIONS.reduce(
  (map, track) => {
    const nextTracks = map.get(track.styleId) ?? []
    map.set(track.styleId, [
      ...nextTracks,
      {
        id: track.id,
        provider: track.provider,
        providerLabel: track.providerLabel,
        title: track.title,
        artist: track.artist,
        audioUrl: track.audioUrl,
        trackUrl: track.trackUrl,
        providerUrl: track.providerUrl,
        licenseLabel: track.licenseLabel,
        isFallback: track.isFallback,
      },
    ])
    return map
  },
  new Map<MusicStyleId, MusicTrackDescriptor[]>()
)

export const LOCAL_FALLBACK_TRACKS: MusicTrackDescriptor[] = LOCAL_FALLBACK_TRACK_DEFINITIONS.map((track) => ({
  id: track.id,
  provider: track.provider,
  providerLabel: track.providerLabel,
  title: track.title,
  artist: track.artist,
  audioUrl: track.audioUrl,
  trackUrl: track.trackUrl,
  providerUrl: track.providerUrl,
  licenseLabel: track.licenseLabel,
  isFallback: track.isFallback,
}))

export function getLocalFallbackTracksForStyle(styleId: MusicStyleId): MusicTrackDescriptor[] {
  const tracks = LOCAL_FALLBACK_TRACKS_BY_STYLE.get(styleId)
  return tracks && tracks.length > 0 ? tracks : LOCAL_FALLBACK_TRACKS
}
